### ISSUE TITLE
Raycast extension 설치하는 방법 문의드려요.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [g6ling/Naver-Dictionary-Raycast#2]
@g6ling 안녕하세요, 먼저 좋은 익스텐션 개발해주셔서 감사합니다. 

Raycast 익스텐션에 이제 막 관심 가지게된 초심자입니다. 이 저장소와 같은 Raycast extension 저장소의 코드를 Raycast에 설치(import)하는 공식적인 방법이 있는지 문의드려요.

일단 https://developers.raycast.com/information/cli 가이드에 따라 `npx ray develop` 를 실행하니 개발 모드로 Raycast에 import 되고 auto reload를 위해 프로세스가 떠있는 것 같은데요,

```
$ npx ray develop
info  -  entry points [src/nae.tsx src/naj.tsx src/nah.tsx src/nak.tsx src/nak.tsx src/nac.tsx src/naf.tsx src/nad.tsx src/nas.tsx src/nav.tsx]
ready -  built extension successfully
```

이 프로세스를 죽여도 import된 extension이 Raycast에 남아있는 것 같아요. 그래서 지금은 이렇게 사용하고 있습니다.

문의드리고 싶은건, 저는 `Naver-Dictionary-Raycast` 익스텐션을 개발할 목적이 아닌 단순 "사용" 목적으로 설치하고 싶은데, `develop` 명령어는 "개발"을 위한 명령어 같아서, 혹시 "사용"을 위한 import 명령어나 다른 방법이 있는지 문의드려요.

**Comment by choru-k** [comment]
예전에는 Raycast 에서 특정국가나 특정집단만을 위한 extension publish 을 허용하지 않았는데, 다시 찾아보니 그러한 규칙이 없어졌네요.
근시일 내에 publish 진행하도록 하겠습니다.
만약 publish 된다면 다른 extension 처럼 설치가 가능할 것으로 생각됩니다.
그전까지는 위의 방법이외는 없을 것 같습니다.
